#!/usr/bin/env Rscript
# Test obs.sumstat.ngs() against pre-computed stdpopsim summary statistics.
#
# This script:
#   1. Loads PipeMaster model objects from test_models.RData
#   2. Runs obs.sumstat.ngs() on PHYLIP files generated by stdpopsim
#   3. Compares results with pre-computed Python-based summary statistics
#   4. Reports whether column names and values match expectations

library(PipeMaster)

# ============================================================================
# Setup
# ============================================================================
# Determine script directory
args <- commandArgs(trailingOnly=FALSE)
script_arg <- grep("--file=", args, value=TRUE)
if (length(script_arg) > 0) {
  test_dir <- dirname(normalizePath(sub("--file=", "", script_arg)))
} else {
  test_dir <- "data_to_test"
}
setwd(test_dir)

load("test_models.RData")

cat("=======================================================\n")
cat("  Testing obs.sumstat.ngs() with stdpopsim PHYLIP data\n")
cat("=======================================================\n\n")

n_pass <- 0
n_fail <- 0

report <- function(test_name, passed, msg="") {
  if (passed) {
    cat(sprintf("  [PASS] %s\n", test_name))
    n_pass <<- n_pass + 1
  } else {
    cat(sprintf("  [FAIL] %s -- %s\n", test_name, msg))
    n_fail <<- n_fail + 1
  }
}

# ============================================================================
# Test 1: Vaquita2Epoch (single population, PHYLIP)
# ============================================================================
cat("--- Test 1: Vaquita2Epoch (single pop, 10000 loci, PHYLIP) ---\n")

pop_assign_vaq <- read.table("pop_assign_Vaquita2Epoch.txt", header=FALSE)
phylip_path_vaq <- normalizePath("phylip_Vaquita2Epoch.phy")

cat("  Running obs.sumstat.ngs()...\n")
obs_vaq <- obs.sumstat.ngs(
  model          = Vaquita2Epoch,
  path.to.phylip = phylip_path_vaq,
  pop.assign     = pop_assign_vaq,
  ncores         = 10
)
cat("  Done.\n\n")

# Check 1a: No errors (if we got here, it passed)
report("Vaquita obs.sumstat.ngs() completes without error", TRUE)

# Check 1b: Output is a matrix with 1 row
report("Vaquita result is a 1-row matrix",
       is.matrix(obs_vaq) && nrow(obs_vaq) == 1,
       sprintf("got %s with %d rows", class(obs_vaq), nrow(obs_vaq)))

# Check 1c: Column names match expected pattern
vaq_colnames <- colnames(obs_vaq)
expected_stats_1pop <- c("segs", "pi", "w", "tajd", "dvk", "dvh")
expected_moments <- c("mean", "var", "skew", "kurt")
expected_cols_1pop <- paste0("s_", rep(expected_moments, length(expected_stats_1pop)),
                              "_", rep(expected_stats_1pop, each=length(expected_moments)))
report("Vaquita column names match expected pattern",
       all(expected_cols_1pop %in% vaq_colnames),
       sprintf("missing: %s", paste(setdiff(expected_cols_1pop, vaq_colnames), collapse=", ")))

# Check 1d: Compare with pre-computed Python stats
precomp_vaq <- read.table("observed_sumstats_Vaquita2Epoch.txt", header=TRUE, sep="\t")
cat("\n  Comparison of obs.sumstat.ngs() vs Python pre-computed (Vaquita):\n")
cat("  Note: differences expected due to msABC vs Python stat computation\n\n")

common_cols <- intersect(colnames(obs_vaq), colnames(precomp_vaq))
cat(sprintf("  Matching columns: %d of %d (R) / %d (Python)\n",
            length(common_cols), ncol(obs_vaq), ncol(precomp_vaq)))

report("Vaquita has matching column names with Python",
       length(common_cols) >= length(expected_stats_1pop) * 2,
       sprintf("only %d common columns", length(common_cols)))

if (length(common_cols) > 0) {
  cat(sprintf("\n  %-25s %15s %15s %10s\n", "Statistic", "obs.sumstat.ngs", "Python", "Ratio"))
  cat(paste(rep("-", 70), collapse=""), "\n")
  for (col in common_cols) {
    r_val <- as.numeric(obs_vaq[1, col])
    py_val <- as.numeric(precomp_vaq[1, col])
    if (!is.na(r_val) && !is.na(py_val) && py_val != 0) {
      ratio <- r_val / py_val
    } else {
      ratio <- NA
    }
    cat(sprintf("  %-25s %15.6f %15.6f %10s\n", col,
                ifelse(is.na(r_val), 0, r_val),
                ifelse(is.na(py_val), 0, py_val),
                ifelse(is.na(ratio), "N/A", sprintf("%.3f", ratio))))
  }
}

# Check 1e: Mean segs should be in a reasonable range (>= 0)
mean_segs <- as.numeric(obs_vaq[1, "s_mean_segs"])
report("Vaquita mean seg sites >= 0",
       !is.na(mean_segs) && mean_segs >= 0,
       sprintf("got %s", mean_segs))


# ============================================================================
# Test 2: OutOfAfrica_3G09 (two populations, PHYLIP)
# ============================================================================
cat("\n--- Test 2: OutOfAfrica_3G09 (2 pops, 10000 loci, PHYLIP) ---\n")

pop_assign_ooa <- read.table("pop_assign_OutOfAfrica_3G09.txt", header=FALSE)
phylip_path_ooa <- normalizePath("phylip_OutOfAfrica_3G09.phy")

cat("  Running obs.sumstat.ngs()...\n")
obs_ooa <- obs.sumstat.ngs(
  model          = OutOfAfrica_3G09,
  path.to.phylip = phylip_path_ooa,
  pop.assign     = pop_assign_ooa,
  ncores         = 10
)
cat("  Done.\n\n")

# Check 2a: No errors
report("OutOfAfrica obs.sumstat.ngs() completes without error", TRUE)

# Check 2b: Output is a matrix with 1 row
report("OutOfAfrica result is a 1-row matrix",
       is.matrix(obs_ooa) && nrow(obs_ooa) == 1,
       sprintf("got %s with %d rows", class(obs_ooa), nrow(obs_ooa)))

# Check 2c: Column names include per-pop stats and pairwise stats
ooa_colnames <- colnames(obs_ooa)
expected_2pop_patterns <- c("segs_1", "segs_2", "pi_1", "pi_2",
                             "Fst", "shared_1_2", "private_1_2",
                             "dvk_1", "dvk_2")
found_patterns <- sapply(expected_2pop_patterns, function(p) any(grepl(p, ooa_colnames, fixed=TRUE)))
report("OutOfAfrica has expected 2-pop column patterns",
       all(found_patterns),
       sprintf("missing patterns: %s", paste(names(found_patterns)[!found_patterns], collapse=", ")))

# Check 2d: Compare with pre-computed Python stats
precomp_ooa <- read.table("observed_sumstats_OutOfAfrica_3G09.txt", header=TRUE, sep="\t")
common_cols_ooa <- intersect(colnames(obs_ooa), colnames(precomp_ooa))
cat(sprintf("\n  Matching columns: %d of %d (R) / %d (Python)\n",
            length(common_cols_ooa), ncol(obs_ooa), ncol(precomp_ooa)))

report("OutOfAfrica has matching column names with Python",
       length(common_cols_ooa) >= 10,
       sprintf("only %d common columns", length(common_cols_ooa)))

# Print comparison table for key stats (means and variances only, for brevity)
mean_cols <- grep("^s_mean_", common_cols_ooa, value=TRUE)
var_cols <- grep("^s_var_", common_cols_ooa, value=TRUE)
key_cols <- c(mean_cols, var_cols)

if (length(key_cols) > 0) {
  cat(sprintf("\n  %-30s %15s %15s %10s\n", "Statistic", "obs.sumstat.ngs", "Python", "Ratio"))
  cat(paste(rep("-", 75), collapse=""), "\n")
  for (col in key_cols) {
    r_val <- as.numeric(obs_ooa[1, col])
    py_val <- as.numeric(precomp_ooa[1, col])
    if (!is.na(r_val) && !is.na(py_val) && py_val != 0) {
      ratio <- r_val / py_val
    } else {
      ratio <- NA
    }
    cat(sprintf("  %-30s %15.6f %15.6f %10s\n", col,
                ifelse(is.na(r_val), 0, r_val),
                ifelse(is.na(py_val), 0, py_val),
                ifelse(is.na(ratio), "N/A", sprintf("%.3f", ratio))))
  }
}

# Check 2e: Mean seg sites for pop1 should be positive (OutOfAfrica has variation)
mean_segs_1 <- as.numeric(obs_ooa[1, "s_mean_segs_1"])
report("OutOfAfrica mean seg sites pop1 > 0",
       !is.na(mean_segs_1) && mean_segs_1 > 0,
       sprintf("got %s", mean_segs_1))

# Check 2f: Fst should be between 0 and 1
mean_fst <- as.numeric(obs_ooa[1, "s_mean_Fst"])
report("OutOfAfrica mean Fst in [0,1]",
       !is.na(mean_fst) && mean_fst >= 0 && mean_fst <= 1,
       sprintf("got %s", mean_fst))

# ============================================================================
# Save obs.sumstat.ngs() results for use as reference in sim.sumstat() tests
# ============================================================================
cat("\n--- Saving obs.sumstat.ngs() results ---\n")

observed_msABC_Vaquita2Epoch <- obs_vaq
observed_msABC_OutOfAfrica_3G09 <- obs_ooa

save(
  observed_msABC_Vaquita2Epoch,
  observed_msABC_OutOfAfrica_3G09,
  file = "observed_msABC_sumstats.RData"
)
cat("  Saved observed_msABC_sumstats.RData\n")
cat(sprintf("    - observed_msABC_Vaquita2Epoch      (1-pop, %d columns)\n", ncol(obs_vaq)))
cat(sprintf("    - observed_msABC_OutOfAfrica_3G09  (2-pop, %d columns)\n", ncol(obs_ooa)))

# Also write as tab-separated text for easy inspection
write.table(obs_vaq, "observed_msABC_Vaquita2Epoch.txt",
            sep="\t", row.names=FALSE, quote=FALSE)
write.table(obs_ooa, "observed_msABC_OutOfAfrica_3G09.txt",
            sep="\t", row.names=FALSE, quote=FALSE)
cat("  Saved tab-separated text files\n")

# ============================================================================
# Summary
# ============================================================================
cat("\n=======================================================\n")
cat(sprintf("  Results: %d passed, %d failed\n", n_pass, n_fail))
cat("=======================================================\n")

if (n_fail > 0) {
  cat("\nSome tests failed. This may indicate a bug or an expected\n")
  cat("difference between msABC and Python stat computation.\n")
}
