#' Grid search for parameter space exploration
#'
#' @description Evaluates a grid of parameter combinations by simulating under each
#'   combination and computing the distance to observed data. Useful for identifying
#'   productive parameter regions before running full ABC reference tables.
#'
#' @param model A model object built by main.menu.gui() with data structure set
#'   via get.data.structure().
#' @param observed Named numeric vector of observed summary statistics or SFS bins.
#' @param grid Optional data.frame with columns named after model parameters.
#'   If NULL, auto-generated on log scale from model priors using \code{n_points}.
#' @param n_points Number of grid points per parameter when auto-generating grid.
#'   Default is 10.
#' @param n_reps Number of replicates per grid cell. Default is 10.
#' @param type Character. Either \code{"sumstat"} or \code{"sfs"}. Default is \code{"sumstat"}.
#' @param use.alpha Logical. If TRUE the most recent population size change will be
#'   exponential. Default is FALSE.
#' @param mu.rates Mutation rate specification. Either a single numeric value (fixed rate
#'   for all loci), a list specifying a distribution (e.g.,
#'   \code{list("rtnorm", n, mean, sd, lower)}), or NULL to sample from model priors.
#'   Default is NULL.
#' @param ncores Number of cores for parallel execution via mclapply. Default is 1.
#' @param one.snp Logical. For SFS type: if TRUE, one SNP per locus. Default is FALSE.
#' @param folded Logical. For SFS type: if TRUE, fold the SFS. Default is FALSE.
#' @param method Character. For SFS type: \code{"stochastic"} or \code{"expected"}.
#'   Default is \code{"stochastic"}.
#' @param monomorphic Logical. For SFS type: if TRUE, prepend monomorphic bin.
#'   Default is FALSE.
#' @return A data.frame with grid parameter columns and a \code{distance} column,
#'   sorted by distance (ascending). Has attributes \code{"simulated"} (matrix of all
#'   simulated values) and \code{"observed"} (matched observed vector).
#' @examples
#' \dontrun{
#' # Load example model
#' data("A_piscivorus", package = "PipeMaster")
#'
#' # Compute observed stats
#' obs <- obs.sumstat.ngs(model = Is_Ap,
#'                        path.to.phylip = "my_data.phy",
#'                        pop.assign = pop_assign)
#'
#' # Grid search with auto-generated grid (10 points per parameter)
#' result <- grid.search(model = Is_Ap, observed = obs[1, ],
#'                       n_points = 5, n_reps = 5,
#'                       mu.rates = 1e-8, ncores = 4)
#'
#' # Inspect top parameter combinations
#' head(result)
#'
#' # Custom grid
#' my_grid <- expand.grid(
#'   Ne0.pop1 = 10^seq(3, 6, length.out = 5),
#'   Ne0.pop2 = 10^seq(3, 6, length.out = 5),
#'   join1    = 10^seq(4, 6, length.out = 5)
#' )
#' result2 <- grid.search(model = Is_Ap, observed = obs[1, ],
#'                        grid = my_grid, n_reps = 10, ncores = 4)
#' }
#' @author Marcelo Gehara
#' @export
grid.search <- function(model, observed, grid = NULL, n_points = 10, n_reps = 10,
                        type = c("sumstat", "sfs"), use.alpha = FALSE,
                        mu.rates = NULL, ncores = 1,
                        one.snp = FALSE, folded = FALSE,
                        method = c("stochastic", "expected"),
                        monomorphic = FALSE) {

  type <- match.arg(type)
  method <- match.arg(method)

  if(is.null(model$flags) || is.null(model$I) || is.null(model$loci))
    stop("model must be a PipeMaster model object generated by main.menu.gui()")

  if(model$I[1, 1] == "genomic")
    stop("Model needs data structure. Use get.data.structure() first.")

  ## ---- Auto-grid from model priors ----
  if(is.null(grid)) {
    tab <- get.prior.table(model)
    param_lists <- list()
    for(i in 1:nrow(tab)) {
      lo <- as.numeric(tab$prior.1[i])
      hi <- as.numeric(tab$prior.2[i])
      if(lo > 0 && hi > 0) {
        param_lists[[tab$Parameter[i]]] <- 10^seq(log10(lo), log10(hi),
                                                   length.out = n_points)
      } else {
        param_lists[[tab$Parameter[i]]] <- seq(lo, hi, length.out = n_points)
      }
    }
    grid <- expand.grid(param_lists)
  }

  param_names <- colnames(grid)

  ## ---- Build parameter location map ----
  # Maps each parameter name to its position in model$flags
  par_map <- list()
  for(pname in param_names) {
    found <- FALSE
    for(fname in names(model$flags)) {
      flag <- model$flags[[fname]]
      if(is.null(flag)) next
      if(is.null(nrow(flag))) {
        # Nested list (en has $size/$time, em has $size/$time)
        for(sname in names(flag)) {
          mat <- flag[[sname]]
          row_idx <- which(mat[, 1] == pname)
          if(length(row_idx) == 1) {
            par_map[[pname]] <- list(flag = fname, sub = sname, row = row_idx)
            found <- TRUE
            break
          }
        }
      } else {
        row_idx <- which(flag[, 1] == pname)
        if(length(row_idx) == 1) {
          par_map[[pname]] <- list(flag = fname, sub = NULL, row = row_idx)
          found <- TRUE
        }
      }
      if(found) break
    }
    if(!found)
      stop("Parameter '", pname, "' not found in model$flags")
  }

  ## ---- Setup locfile ----
  locfile <- get.locfile(model)
  nloci_rows <- nrow(locfile)
  npop <- as.numeric(model$I[1, 3])

  tmpdir <- tempfile("grid_search_")
  dir.create(tmpdir)
  on.exit(unlink(tmpdir, recursive = TRUE))

  locfile_path <- file.path(tmpdir, ".1locfile.txt")
  write.table(locfile, locfile_path, row.names = FALSE, col.names = TRUE,
              quote = FALSE, sep = " ")

  ## ---- Build all tasks ----
  tasks <- grid[rep(1:nrow(grid), each = n_reps), , drop = FALSE]
  tasks$grid_id <- rep(1:nrow(grid), each = n_reps)
  rownames(tasks) <- NULL
  ntasks <- nrow(tasks)

  ## ---- Build commands and mu_mat ----
  commands <- character(ntasks)
  mu_mat <- matrix(0, nrow = nloci_rows, ncol = ntasks)

  for(i in 1:ntasks) {
    # Clone model and inject grid parameters
    m <- model
    m$conds <- lapply(m$conds, function(x) NULL)

    for(pname in param_names) {
      loc <- par_map[[pname]]
      val <- as.character(tasks[[pname]][i])
      if(is.null(loc$sub)) {
        m$flags[[loc$flag]][loc$row, 4] <- val
        m$flags[[loc$flag]][loc$row, 5] <- val
        m$flags[[loc$flag]][loc$row, 6] <- "runif"
      } else {
        m$flags[[loc$flag]][[loc$sub]][loc$row, 4] <- val
        m$flags[[loc$flag]][[loc$sub]][loc$row, 5] <- val
        m$flags[[loc$flag]][[loc$sub]][loc$row, 6] <- "runif"
      }
    }

    # Sample mu rates
    if(is.numeric(mu.rates) && length(mu.rates) == 1) {
      rates <- rep(mu.rates, nloci_rows)
    } else if(is.list(mu.rates)) {
      rates <- do.call(mu.rates[[1]], args = mu.rates[2:length(mu.rates)])
      rates <- rep(rates, each = npop)
    } else {
      rates <- sample.mu.rates(m)[[1]]
    }
    mu_mat[, i] <- rates

    # Build msABC command
    com <- msABC.commander(m, use.alpha = use.alpha, arg = 1)
    cmd <- com[[1]]
    cmd <- gsub(".1locfile.txt", locfile_path, cmd, fixed = TRUE)
    commands[i] <- cmd
  }

  ## ---- Execute simulations ----
  cat("PipeMaster:: Grid search:", nrow(grid), "cells x", n_reps, "reps =",
      ntasks, "total simulations\n")
  t0 <- proc.time()

  if(type == "sumstat") {
    sim_mat <- .grid.run.sumstat(commands, mu_mat, ncores)
  } else {
    pop_sizes_vec <- as.integer(
      matrix(as.numeric(model$I[, 4:(3 + npop)]), ncol = npop)[1, ]
    )
    sim_mat <- .grid.run.sfs(commands, mu_mat, pop_sizes_vec, one.snp, method,
                              folded, monomorphic, model, npop, ncores)
  }

  elapsed <- (proc.time() - t0)["elapsed"]
  cat(sprintf("PipeMaster:: %d simulations completed in %.1f sec (%.0f sims/sec)\n",
              ntasks, elapsed, ntasks / elapsed))

  ## ---- Match observed columns ----
  common <- intersect(names(observed), colnames(sim_mat))
  if(length(common) == 0)
    stop("No matching statistic names between 'observed' and simulated output.\n",
         "  Observed names: ",
         paste(head(names(observed), 5), collapse = ", "),
         ifelse(length(names(observed)) > 5, ", ...", ""), "\n",
         "  Simulated names: ",
         paste(head(colnames(sim_mat), 5), collapse = ", "),
         ifelse(ncol(sim_mat) > 5, ", ...", ""))

  if(length(common) < length(names(observed)))
    cat("PipeMaster:: Using", length(common), "of", length(names(observed)),
        "observed statistics (matched by name)\n")

  obs_vec <- observed[common]
  sim_sub <- sim_mat[, common, drop = FALSE]

  ## ---- Compute standardized Euclidean distance ----
  sds <- apply(sim_sub, 2, sd, na.rm = TRUE)
  sds[sds == 0 | is.na(sds)] <- 1
  obs_std <- obs_vec / sds
  sim_std <- sweep(sim_sub, 2, sds, "/")
  distances <- sqrt(rowSums(sweep(sim_std, 2, obs_std)^2, na.rm = TRUE))

  ## ---- Aggregate by grid cell ----
  tasks$distance <- distances
  agg_formula <- as.formula(paste("distance ~",
                                   paste(param_names, collapse = " + ")))
  result <- aggregate(agg_formula, data = tasks, FUN = mean)
  result <- result[order(result$distance), ]
  rownames(result) <- NULL

  attr(result, "simulated") <- sim_mat
  attr(result, "observed") <- obs_vec

  result
}


# ---- Internal: run sumstat batch simulations ----
.grid.run.sumstat <- function(commands, mu_mat, ncores) {
  ntasks <- length(commands)

  run_batch <- function(idx) {
    outputs <- .Call("msABC_batch_call", commands[idx],
                     mu_mat[, idx, drop = FALSE], NULL,
                     PACKAGE = "PipeMaster")
    .parse.sumstat.outputs(outputs)
  }

  if(ncores <= 1) {
    sim_mat <- run_batch(1:ntasks)
  } else {
    chunks <- split(1:ntasks, cut(1:ntasks, ncores, labels = FALSE))
    results <- parallel::mclapply(chunks, run_batch, mc.cores = ncores)
    sim_mat <- do.call(rbind, results)
  }
  sim_mat
}


# ---- Internal: parse msABC batch sumstat outputs ----
.parse.sumstat.outputs <- function(outputs) {
  sumstats_list <- lapply(strsplit(outputs, "\n", fixed = TRUE), function(lines) {
    tab <- read.table(text = lines, header = TRUE, sep = "\t")
    if("X" %in% colnames(tab))
      tab <- tab[, colnames(tab) != "X", drop = FALSE]
    cols <- grep("thomson|ZnS|FayWuH|fwh", colnames(tab))
    if(length(cols) != 0) tab <- tab[, -cols, drop = FALSE]
    tab
  })
  as.matrix(do.call(rbind, sumstats_list))
}


# ---- Internal: run SFS batch simulations ----
.grid.run.sfs <- function(commands, mu_mat, pop_sizes_vec, one.snp, method,
                           folded, monomorphic, model, npop, ncores) {
  ntasks <- length(commands)
  nsam <- sum(pop_sizes_vec)

  run_batch <- function(idx) {
    sfs_mat <- .Call("msABC_sfs_batch_call", commands[idx],
                     mu_mat[, idx, drop = FALSE],
                     pop_sizes_vec, one.snp, method,
                     PACKAGE = "PipeMaster")

    if(folded && npop == 1) {
      sfs_mat <- t(apply(sfs_mat, 1, fold_sfs))
    }

    if(monomorphic) {
      total_sites <- sum(as.numeric(model$loci[, 2]))
      mono_col <- total_sites - rowSums(sfs_mat)
      sfs_mat <- cbind(mono_col, sfs_mat)
    }

    sfs_mat
  }

  if(ncores <= 1) {
    sim_mat <- run_batch(1:ntasks)
  } else {
    chunks <- split(1:ntasks, cut(1:ntasks, ncores, labels = FALSE))
    results <- parallel::mclapply(chunks, run_batch, mc.cores = ncores)
    sim_mat <- do.call(rbind, results)
  }

  # Assign column names following sim.sfs conventions
  if(npop == 1) {
    sfs_len <- nsam - 1
    if(folded) {
      folded_len <- ncol(sim_mat) - as.integer(monomorphic)
      sfs_names <- paste0("sfs_fold_", seq(0, folded_len - 1))
    } else {
      sfs_names <- paste0("sfs_", seq(0, sfs_len - 1))
    }
  } else {
    idx_grid <- expand.grid(lapply(pop_sizes_vec, function(n) 0:n))
    sfs_names <- apply(idx_grid, 1, function(x)
      paste0("sfs_", paste(x, collapse = "_")))
  }
  if(monomorphic) {
    sfs_names <- c("sfs_mono", sfs_names)
  }
  colnames(sim_mat) <- sfs_names

  sim_mat
}


#' Update model priors from grid search results
#'
#' @description Narrows model priors to the productive parameter region identified
#'   by \code{\link{grid.search}}. For each parameter, the new uniform prior spans
#'   the min–max range of the top grid cells (by distance), with optional padding
#'   in log space. This is the recommended step between grid search and full ABC.
#'
#' @param model A PipeMaster model object (with \code{model$flags}).
#' @param grid.results A data.frame returned by \code{\link{grid.search}}, with
#'   parameter columns and a \code{distance} column.
#' @param tol Fraction of top grid cells to use (default 0.05 = top 5\%).
#' @param padding Fractional margin in log space beyond min/max of top cells
#'   (default 0.1).
#' @return The model with updated (narrowed) priors.
#' @examples
#' \dontrun{
#' result <- grid.search(model = my_model, observed = obs,
#'                       n_points = 10, n_reps = 10, ncores = 4)
#' my_model <- update.priors.from.grid(my_model, result, tol = 0.05, padding = 0.1)
#' }
#' @author Marcelo Gehara
#' @export
update.priors.from.grid <- function(model, grid.results, tol = 0.05, padding = 0.1) {

  ## ---- Validate inputs ----
  if (!"distance" %in% colnames(grid.results))
    stop("'grid.results' must contain a 'distance' column")

  old_tab <- get.prior.table(model)
  param_cols <- setdiff(colnames(grid.results), "distance")

  missing <- setdiff(param_cols, old_tab$Parameter)
  if (length(missing) > 0)
    stop("Parameters not found in model: ", paste(missing, collapse = ", "))

  ## ---- Select top grid cells ----
  grid.results <- grid.results[order(grid.results$distance), ]
  n_top <- max(1, ceiling(nrow(grid.results) * tol))
  top <- grid.results[1:n_top, , drop = FALSE]

  ## ---- Build new prior table ----
  new_tab <- data.frame(
    Parameter    = param_cols,
    prior.1      = NA_character_,
    prior.2      = NA_character_,
    distribution = "runif",
    stringsAsFactors = FALSE
  )

  cat("PipeMaster:: Updating priors from top", n_top, "of", nrow(grid.results),
      "grid cells (tol =", tol, ", padding =", padding, ")\n")

  for (i in seq_along(param_cols)) {
    pname <- param_cols[i]
    vals  <- top[[pname]]
    min_val <- min(vals)
    max_val <- max(vals)

    ## Old range for display
    old_row <- which(old_tab$Parameter == pname)
    old_lo  <- as.numeric(old_tab$prior.1[old_row])
    old_hi  <- as.numeric(old_tab$prior.2[old_row])

    ## Compute new range with padding in log space
    if (min_val == max_val) {
      new_min <- 10^(log10(min_val) - 0.5)
      new_max <- 10^(log10(max_val) + 0.5)
    } else {
      log_range <- log10(max_val) - log10(min_val)
      new_min   <- 10^(log10(min_val) - padding * log_range)
      new_max   <- 10^(log10(max_val) + padding * log_range)
    }

    new_tab$prior.1[i] <- as.character(new_min)
    new_tab$prior.2[i] <- as.character(new_max)

    cat(sprintf("  %-20s: [%.4g, %.4g] -> [%.4g, %.4g]\n",
                pname, old_lo, old_hi, new_min, new_max))
  }

  ## ---- Apply via existing update.priors() ----
  model <- update.priors(new_tab, model)
  model
}
