#' Simulate both summary statistics and SFS in a single coalescent pass
#' @description This function simulates both summary statistics and the Site Frequency Spectrum
#'              from a single coalescent simulation run, cutting simulation time in half compared
#'              to running \code{sim.sumstat()} and \code{sim.sfs()} separately. The output is
#'              written to a single file with columns: parameters | summary statistics | SFS bins.
#' @param model A model object built by the main.menu.gui() function.
#' @param nsim.blocks Number of blocks to simulate. Total simulations = nsim.blocks x block.size (x ncores).
#' @param block.size Number of simulations per block. Default is 10.
#' @param path Path to write the output. Default is working directory.
#' @param output.name String. The prefix of the output file names.
#' @param use.alpha Logical. If TRUE the most recent population size change will be exponential. Default is FALSE.
#' @param mu.rates List. Distribution to sample mutation rates. See \code{sim.sumstat()} for details.
#' @param rec.rates List. Distribution to sample recombination rates. See \code{sim.sumstat()} for details.
#' @param one.snp Logical. If TRUE, one segregating site is randomly sampled per locus for the SFS. Default is FALSE.
#' @param folded Logical. If TRUE the SFS will be folded. Default is FALSE.
#' @param method Character string: \code{"stochastic"} (default) or \code{"expected"} for SFS computation.
#' @param monomorphic Logical. If TRUE, a monomorphic bin is prepended to the SFS. Default is FALSE.
#' @param variable_samples Logical. If TRUE, allows variable sample sizes across
#'   loci but skips SFS computation (returns parameters + summary statistics only).
#'   Use \code{optimize.sfs.model()} to downsample to uniform sizes if SFS is needed.
#'   Default is FALSE.
#' @param append.sims Logical. If TRUE simulations will be appended. Default is FALSE.
#' @param ncores Number of cores for parallel execution. Default is 1.
#' @return Writes \code{SIMS_<output.name>.txt} with columns: parameters, summary statistics, and SFS bins.
#'         When \code{variable_samples = TRUE}, only parameters and summary statistics are written (no SFS).
#' @author Marcelo Gehara
#' @export
sim.sumstats <- function(model, nsim.blocks, block.size = 10,
                          path = getwd(), output.name,
                          use.alpha = FALSE,
                          mu.rates = NULL, rec.rates = NULL,
                          one.snp = FALSE, folded = FALSE,
                          method = c("stochastic", "expected"),
                          monomorphic = FALSE,
                          variable_samples = FALSE,
                          append.sims = FALSE, ncores = 1,
                          .parent.pid.file = NULL) {

  WD <- getwd()
  method <- match.arg(method)

  if(!inherits(model, "Model")) {
    stop("First argument should be an object of class Model generated by the main.menu.gui() function.")
  }
  if(model$I[1,1] == "genomic") {
    stop("You need to get the data structure first. See function get.data.structure")
  }

  # Check per-population sample sizes across loci
  npop <- as.numeric(model$I[1, 3])
  pop_cols <- 4:(3 + npop)
  pop_sizes_mat <- matrix(as.numeric(model$I[, pop_cols]), ncol = npop)
  uniform_samples <- nrow(unique(pop_sizes_mat)) == 1

  if(!uniform_samples && !variable_samples) {
    stop("Per-population sample sizes vary across loci. SFS cannot be computed.\n",
         "  Either use optimize.sfs.model() to downsample to uniform sizes,\n",
         "  or set variable_samples = TRUE to skip SFS (summary statistics only).")
  }
  skip_sfs <- !uniform_samples  # skip SFS when samples vary

  pop_sizes_vec <- as.integer(pop_sizes_mat[1, ])
  nsam <- sum(pop_sizes_vec)

  setwd(path)
  on.exit(setwd(WD))

  locfile <- PipeMaster:::get.locfile(model)
  outfile <- paste0("SIMS_", output.name, ".txt")

  ############### Header discovery and writing
  if(append.sims == FALSE) {
    # Discover sumstat column names via one test run
    com <- PipeMaster:::msABC.commander(model, use.alpha = use.alpha, arg = 1)
    write.table(locfile, paste(".", 1, "locfile.txt", sep = ""),
                row.names = FALSE, col.names = TRUE, quote = FALSE, sep = " ")
    x <- strsplit(run.msABC(com[[1]]), "\t")
    ss.nam <- x[1][[1]]
    cols <- grep("thomson", ss.nam)
    cols <- c(cols, grep("FayWuH", ss.nam))
    cols <- c(cols, grep("fwh", ss.nam))
    if(length(cols) != 0) ss.nam <- ss.nam[-cols]
    par.names <- c(com[[2]][1, ], "mean.rate", "sd.rate")

    # SFS column names (skip when variable samples)
    if(!skip_sfs) {
      if(npop == 1) {
        sfs_len <- floor(nsam / 2)
        if(folded) {
          folded_len <- length(fold_sfs(numeric(nsam - 1)))
          sfs.names <- paste0("sfs_fold_", seq(0, folded_len - 1))
        } else {
          sfs.names <- paste0("sfs_", seq(0, sfs_len - 1))
        }
      } else {
        idx_grid <- expand.grid(lapply(pop_sizes_vec, function(n) 0:n))
        sfs.names <- apply(idx_grid, 1, function(x) paste0("sfs_", paste(x, collapse = "_")))
      }
      if(monomorphic) {
        sfs.names <- c("sfs_mono", sfs.names)
      }
    }

    # Single header: params | sumstats | SFS (when uniform)
    nam <- if(skip_sfs) c(par.names, ss.nam) else c(par.names, ss.nam, sfs.names)
    write.table(t(nam), file = outfile,
                quote = FALSE, row.names = FALSE, col.names = FALSE,
                append = FALSE, sep = "\t")
  }

  ############### Multi-core path
  if(ncores > 1) {
    abs.path <- normalizePath(getwd())

    # Clean up stale worker dirs and done files
    for(w in 1:ncores) {
      unlink(file.path(abs.path, paste0(".worker_", w)), recursive = TRUE)
      f <- file.path(abs.path, paste0(".worker_", w, ".done"))
      if(file.exists(f)) file.remove(f)
    }

    # Register parent PID + on.exit cleanup (kills workers on exit/error/interrupt)
    pid_file <- file.path(abs.path, ".PM_parent.pid")
    worker_pids_env <- new.env(parent = emptyenv())
    worker_pids_env$pids <- integer(0)
    .pm.register.parent(pid_file, worker_pids_env)

    save(model, nsim.blocks, block.size, use.alpha, mu.rates, rec.rates,
         output.name, one.snp, folded, method, monomorphic, variable_samples,
         file = file.path(abs.path, ".PM_worker_params.RData"))

    worker_script <- paste(
      'args <- commandArgs(TRUE)',
      'worker_id <- as.integer(args[1])',
      'suppressMessages(library(PipeMaster))',
      sprintf('base_path <- "%s"', abs.path),
      'pid_file <- file.path(base_path, ".PM_parent.pid")',
      'load(file.path(base_path, ".PM_worker_params.RData"))',
      'worker_dir <- file.path(base_path, paste0(".worker_", worker_id))',
      'dir.create(worker_dir, showWarnings=FALSE)',
      'sim.sumstats(model=model, nsim.blocks=nsim.blocks, block.size=block.size,',
      '              path=worker_dir, use.alpha=use.alpha, mu.rates=mu.rates,',
      '              rec.rates=rec.rates, one.snp=one.snp, folded=folded,',
      '              method=method, monomorphic=monomorphic,',
      '              variable_samples=variable_samples, append.sims=TRUE,',
      '              output.name=output.name, ncores=1,',
      '              .parent.pid.file=pid_file)',
      'write("done", file.path(base_path, paste0(".worker_", worker_id, ".done")))',
      'quit(save="no")',
      sep = "\n")
    writeLines(worker_script, file.path(abs.path, ".PM_worker.R"))

    start.time <- Sys.time()
    for(w in 1:ncores) {
      pid <- system(paste("Rscript", file.path(abs.path, ".PM_worker.R"), w,
                   ">", file.path(abs.path, paste0(".worker_", w, ".log")), "2>&1 & echo $!"),
             intern = TRUE)
      wpid <- suppressWarnings(as.integer(pid[length(pid)]))
      if (!is.na(wpid)) worker_pids_env$pids <- c(worker_pids_env$pids, wpid)
    }
    cat(paste("PipeMaster:: Launched", ncores, "worker processes"), "\n")

    total_expected <- nsim.blocks * block.size * ncores
    prev_total_sims <- -1
    prev_done_count <- -1
    while(TRUE) {
      Sys.sleep(5)
      done_count <- sum(file.exists(file.path(abs.path, paste0(".worker_", 1:ncores, ".done"))))

      # Count sims across all workers
      total_sims <- 0
      for(w in 1:ncores) {
        wf <- file.path(abs.path, paste0(".worker_", w), paste0("SIMS_", output.name, ".txt"))
        if(file.exists(wf)) {
          n <- as.integer(system(paste("wc -l <", shQuote(wf)), intern = TRUE))
          if(!is.na(n) && n > 0) total_sims <- total_sims + n
        }
      }

      if(total_sims != prev_total_sims || done_count != prev_done_count) {
        elapsed_h <- as.numeric(difftime(Sys.time(), start.time, units = "hours"))
        if(elapsed_h > 0.001 && total_sims > 0) {
          rate <- round(total_sims / elapsed_h)
          remaining <- round(max(0, (total_expected - total_sims) / rate), 2)
        } else {
          rate <- "..."
          remaining <- "..."
        }
        cat(sprintf("PipeMaster:: %d/%d sims (~%s sims/h) | ~%s h remaining | %d/%d workers done\n",
                    total_sims, total_expected, rate, remaining, done_count, ncores))
        prev_total_sims <- total_sims
        prev_done_count <- done_count
      }

      if(done_count >= ncores) break
    }

    cat("Compiling results from workers", sep = "\n")
    outpath <- file.path(abs.path, outfile)
    for(w in 1:ncores) {
      wf <- file.path(abs.path, paste0(".worker_", w), outfile)
      if(file.exists(wf)) {
        worker_data <- readLines(wf)
        if(length(worker_data) > 0) {
          cat(paste(worker_data, collapse = "\n"), "\n", file = outpath, append = TRUE, sep = "")
        }
      }
      unlink(file.path(abs.path, paste0(".worker_", w)), recursive = TRUE)
      f <- file.path(abs.path, paste0(".worker_", w, ".done"))
      if(file.exists(f)) file.remove(f)
    }
    file.remove(file.path(abs.path, ".PM_worker_params.RData"))
    file.remove(file.path(abs.path, ".PM_worker.R"))
    for(w in 1:ncores) {
      f <- file.path(abs.path, paste0(".worker_", w, ".log"))
      if(file.exists(f)) file.remove(f)
    }

    end.time <- Sys.time()
    elapsed_h <- as.numeric(difftime(end.time, start.time, units = "hours"))
    cat(paste0("PipeMaster:: Done! ", total_expected, " simulations in ",
               round(elapsed_h, 3), " hours (~", round(total_expected / elapsed_h), " sims/h)"), "\n")

  } else {
    ############### Single-core path (combined C call)
    nloci_rows <- nrow(locfile)
    npop_loc <- as.numeric(model$I[1, 3])

    sim.combined.func <- function(arg) {
      # Pre-sample all parameters for the block
      commands <- character(block.size)
      mu_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
      rec_mat <- NULL
      par_list <- vector("list", block.size)

      for(i in 1:block.size) {
        if(is.numeric(mu.rates) && length(mu.rates) == 1) {
          rates <- list(rep(mu.rates, nloci_rows), c(mu.rates, 0))
        } else if(is.list(mu.rates)) {
          rates <- do.call(mu.rates[[1]], args = as.list(mu.rates[2:length(mu.rates)]))
          rates <- rep(rates, each = npop_loc)
          rates <- list(rates, c(0, 0))
        } else {
          rates <- sample.mu.rates(model)
        }
        mu_mat[, i] <- rates[[1]]

        if(is.numeric(rec.rates) && length(rec.rates) == 1) {
          r.rates <- rep(rec.rates, nloci_rows)
          if(is.null(rec_mat)) rec_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
          rec_mat[, i] <- r.rates
        } else if(is.list(rec.rates)) {
          r.rates <- do.call(rec.rates[[1]], args = as.list(rec.rates[2:length(rec.rates)]))
          r.rates <- rep(r.rates, each = npop_loc)
          if(is.null(rec_mat)) rec_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
          rec_mat[, i] <- r.rates
        }

        com <- msABC.commander(model, use.alpha = use.alpha, arg = arg)
        commands[i] <- com[[1]]
        par_list[[i]] <- c(com[[2]][2, ], rates[[2]])
        names(par_list[[i]]) <- c(com[[2]][1, ], "mean.rate", "sd.rate")
      }

      # Write locfile ONCE
      write.table(locfile, paste(".", arg, "locfile.txt", sep = ""),
                  row.names = FALSE, col.names = TRUE, quote = FALSE, sep = " ")

      if(skip_sfs) {
        # Variable samples: stats-only path via msABC_batch_call
        outputs <- .Call("msABC_batch_call", commands, mu_mat, rec_mat,
                         PACKAGE = "PipeMaster")

        sumstats_list <- lapply(strsplit(outputs, "\n", fixed = TRUE), function(lines) {
          tab <- read.table(text = lines, header = TRUE, sep = "\t")
          tab <- subset(tab, select = -c(X))
          cols <- grep("thomson", colnames(tab))
          cols <- c(cols, grep("FayWuH", colnames(tab)))
          cols <- c(cols, grep("fwh", colnames(tab)))
          if(length(cols) != 0) tab <- tab[, -cols]
          tab
        })
        sumstats_mat <- do.call(rbind, sumstats_list)
        par_mat <- do.call(rbind, par_list)
        data.frame(cbind(par_mat, sumstats_mat))

      } else {
        # Uniform samples: combined C call produces BOTH text output and SFS
        combined <- .Call("msABC_combined_batch_call", commands, mu_mat, rec_mat,
                          pop_sizes_vec, one.snp, method, monomorphic,
                          PACKAGE = "PipeMaster")

        # Parse sumstat text output (same as sim.sumstat)
        outputs <- combined[[1]]
        sumstats_list <- lapply(strsplit(outputs, "\n", fixed = TRUE), function(lines) {
          tab <- read.table(text = lines, header = TRUE, sep = "\t")
          tab <- subset(tab, select = -c(X))
          cols <- grep("thomson", colnames(tab))
          cols <- c(cols, grep("FayWuH", colnames(tab)))
          cols <- c(cols, grep("fwh", colnames(tab)))
          if(length(cols) != 0) tab <- tab[, -cols]
          tab
        })
        sumstats_mat <- do.call(rbind, sumstats_list)

        # Process SFS
        sfs_mat <- combined[[2]]
        if(npop == 1 && !folded) {
          sfs_mat <- sfs_mat[, 1:floor(nsam / 2), drop = FALSE]
        }
        if(folded && npop == 1) {
          sfs_mat <- t(apply(sfs_mat, 1, fold_sfs))
        }
        if(monomorphic) {
          total_sites <- sum(as.numeric(model$loci[, 2]))
          mono_col <- total_sites - rowSums(sfs_mat)
          sfs_mat <- cbind(mono_col, sfs_mat)
        }

        par_mat <- do.call(rbind, par_list)
        data.frame(cbind(par_mat, sumstats_mat, sfs_mat))
      }
    }

    total.sims <- 0
    for(j in 1:nsim.blocks) {
      # Check if parent process is still alive (workers only)
      if (!is.null(.parent.pid.file) && !.pm.parent.alive(.parent.pid.file)) {
        cat("PipeMaster:: Parent process died, worker exiting.\n")
        return(invisible(NULL))
      }
      start.time <- Sys.time()
      simulations <- sim.combined.func(1)

      cat("Writing simulations to file", sep = "\n")
      write.table(simulations, file = outfile,
                  quote = FALSE, row.names = FALSE, col.names = FALSE,
                  append = TRUE, sep = "\t")

      end.time <- Sys.time()
      total.sims <- total.sims + block.size
      cycle.time <- (as.numeric(end.time) - as.numeric(start.time)) / 60 / 60
      total.time <- cycle.time * nsim.blocks
      passed.time <- cycle.time * j
      remaining.time <- round(total.time - passed.time, 3)
      cat(paste("PipeMaster:: ", total.sims, " (~", round(block.size / cycle.time),
                " sims/h) | ~", remaining.time, " hours remaining", sep = ""), "\n")
    }
    f <- ".1locfile.txt"
    if(file.exists(f)) file.remove(f)
    print("Done!")
  }
}

