#' Simulate summary statistics using msABC
#' @description This function simulates summary statistics using msABC.
#'              It is optimized for nextgen data, but it should also work for sanger.
#'              This will simulate the entire loci, not a single SNP.
#'              You should include all loci in the model object, including invariable ones. Use the get.data.structure function to set up the parameters of the loci - bp and number of individuals - to be simulated.
#' @param model A model object built by the main.menu.gui() function. Both genomic and sanger-type models are allowed.
#' @param use.alpha Logical. If TRUE the most recent population size change will be exponential. If FALSE sudden demographic changes. Default is FALSE.
#'                  This argument changes ONLY the MOST RECENT demographic change.
#' @param nsim.blocks Number of blocks to simulate. The total number of simulations is: nsim.blocks x block.size (x ncores when ncores > 1).
#' @param block.size Simulations are performed in blocks. This argument defines the size of the block in number of simulations, i.e. how many simulations to run per block.
#'                   A block of 1000 will work for most cases. Increase the total number of simulations with nsim.blocks argument.
#' @param path Path to write the output. By default outputs will be saved in the working directory.
#' @param output.name String. The prefix of the output names. Default is "model".
#' @param append.sims Logical. If TRUE simulations will be appended in the last output. Default is FALSE.
#' @param ncores Number of cores for parallel execution. When ncores > 1, separate R worker processes are spawned. Default is 1.
#' @param mu.rates List. Distribution to sample the mutation rates. The first element of the list should be the name of the distribution as a character string. All distributions available in r-base and r-package e1071 are allowed.
#'                   The second element of the list must be the number of loci. The following elements are the parameters of the distribution to be passed on to the r-distribution function.
#'                    Ex.: mu.rates = list("rtnorm", 1000, 1e-9, 1e-9, 0). i.e sample 1000 values using the rtnorm function with mean 1e-9 and SD 1e-9, with lower tail limit at zero.
#' @param rec.rates List. Distribution to sample the recombination rates. The first element of the list should be the name of the distribution as a character string. All distributions available in r-base and r-package e1071 are allowed.
#'                   The second element of the list must be the number of loci. The following elements are the parameters of the distribution to be passed on to the r-distribution function.
#'                    Ex.: rec.rates = list("rtnorm", 1000, 1e-9, 1e-9, 0). i.e sample 1000 values using the rtnorm function with mean 1e-9 and SD 1e-9, with lower tail limit at zero.
#' @return Writes simulations and parameters to the path directory.
#' @examples
#' \dontrun{
#' # Load example demographic models
#' data("A_piscivorus", package = "PipeMaster")
#'
#' # Check model priors
#' get.prior.table(Is)
#'
#' # Quick test run (small block size, single core)
#' tmpdir <- tempdir()
#' sim.sumstat(model = Is,
#'                   nsim.blocks = 1,
#'                   block.size = 10,
#'                   path = tmpdir,
#'                   use.alpha = FALSE,
#'                   output.name = "test_Is",
#'                   ncores = 1)
#'
#' # Read simulated summary statistics
#' sim.data <- read.table(file.path(tmpdir, "SIMS_test_Is.txt"), header = TRUE)
#' head(sim.data)
#'
#' # Production run (more simulations, multiple cores)
#' # sim.sumstat(model = IM,
#' #                   nsim.blocks = 50,
#' #                   block.size = 1000,
#' #                   path = tmpdir,
#' #                   use.alpha = FALSE,
#' #                   output.name = "IM_sims",
#' #                   ncores = 4)
#' }
#' @references Hudson R.R. (2002) Generating samples under a Wright-Fisher neutral model of genetic variation. Bioinformatics, 18, 337–338.
#' @references Pavlidis P., Laurent S., & Stephan W. (2010) msABC: A modification of Hudson's ms to facilitate multi-locus ABC analysis. Molecular Ecology Resources, 10, 723–727.
#' @author Marcelo Gehara
#' @export
sim.sumstat<-function(model, nsim.blocks, path=getwd(), use.alpha=F, mu.rates=NULL, rec.rates = NULL,
                            append.sims=F,block.size=10,output.name,ncores){

  WD<-getwd()

  if(class(model)!="Model"){
    stop("First argument should be an object of class Model generated by the main.menu.gui() function.")
  }
  if(model$I[1,1]=="genomic"){
    stop("You need to get the data structure first. See function get.data.structure")
  }
  # set working directory
  setwd(path)
  on.exit(setwd(WD))

  locfile <- PipeMaster:::get.locfile(model)
  msABC.path <- find.package("PipeMaster")

  if(append.sims==F){
    com <- PipeMaster:::msABC.commander(model,use.alpha=use.alpha,arg=1)
    write.table(locfile,paste(".",1,"locfile.txt",sep=""),row.names = F,col.names = T,quote = F,sep=" ")
    x <- strsplit(run.msABC(com[[1]]),"\t")
    nam<-x[1][[1]]
    #TD_denom <- paste(nam[grep("pi",nam)],nam[grep("_w",nam)],sep="_")
    #nam<-nam[-grep("ZnS",nam)]
    #nam<-nam[-grep("thomson",nam)]
    #cols <- grep("fwh",nam)
    cols <- grep("thomson",nam)
    cols <- c(cols, grep("ZnS",nam))
    cols <- c(cols, grep("FayWuH",nam))
    cols <- c(cols, grep("fwh",nam))
    if(length(cols)!=0) nam <- nam[-cols]
    #nam <- c(nam, TD_denom)
    nam <- c(com[[2]][1,],"mean.rate","sd.rate",nam)
    #t(paste(nam,"_skew",sep="")),t(paste(nam,"_var",sep="")))
    write.table(t(nam),file=paste("SIMS_",output.name,".txt",sep=""),quote=F,row.names = F,col.names = F, append=F,sep="\t")
}

  if(ncores > 1) {
    # === MULTI-CORE: spawn separate R processes ===
    abs.path <- normalizePath(getwd())

    # Clean up stale worker dirs and done files from previous (possibly killed) runs
    for(w in 1:ncores) {
      unlink(file.path(abs.path, paste0(".worker_", w)), recursive = TRUE)
      f <- file.path(abs.path, paste0(".worker_", w, ".done"))
      if(file.exists(f)) file.remove(f)
    }

    save(model, nsim.blocks, block.size, use.alpha, mu.rates, rec.rates, output.name,
         file = file.path(abs.path, ".PM_worker_params.RData"))

    worker_script <- paste(
      'args <- commandArgs(TRUE)',
      'worker_id <- as.integer(args[1])',
      'suppressMessages(library(PipeMaster))',
      sprintf('base_path <- "%s"', abs.path),
      'load(file.path(base_path, ".PM_worker_params.RData"))',
      'worker_dir <- file.path(base_path, paste0(".worker_", worker_id))',
      'dir.create(worker_dir, showWarnings=FALSE)',
      'sim.sumstat(model=model, nsim.blocks=nsim.blocks, block.size=block.size,',
      '                  path=worker_dir, use.alpha=use.alpha, mu.rates=mu.rates,',
      '                  rec.rates=rec.rates, append.sims=TRUE,',
      '                  output.name=output.name, ncores=1)',
      'write("done", file.path(base_path, paste0(".worker_", worker_id, ".done")))',
      'quit(save="no")',
      sep = "\n")
    writeLines(worker_script, file.path(abs.path, ".PM_worker.R"))

    start.time <- Sys.time()
    for(w in 1:ncores) {
      system(paste("Rscript", file.path(abs.path, ".PM_worker.R"), w,
                   ">", file.path(abs.path, paste0(".worker_", w, ".log")), "2>&1"),
             wait = FALSE)
    }
    cat(paste("PipeMaster:: Launched", ncores, "worker processes"), "\n")

    total_expected <- nsim.blocks * block.size * ncores
    prev_total_sims <- -1
    prev_done_count <- -1
    while(TRUE) {
      Sys.sleep(5)
      done_count <- sum(file.exists(file.path(abs.path, paste0(".worker_", 1:ncores, ".done"))))

      # Count sims across all workers
      total_sims <- 0
      for(w in 1:ncores) {
        wf <- file.path(abs.path, paste0(".worker_", w), paste0("SIMS_", output.name, ".txt"))
        if(file.exists(wf)) {
          n <- as.integer(system(paste("wc -l <", shQuote(wf)), intern = TRUE))
          if(!is.na(n) && n > 0) total_sims <- total_sims + n
        }
      }

      # Only print when progress changes
      if(total_sims != prev_total_sims || done_count != prev_done_count) {
        elapsed_h <- as.numeric(difftime(Sys.time(), start.time, units = "hours"))
        if(elapsed_h > 0.001 && total_sims > 0) {
          rate <- round(total_sims / elapsed_h)
          remaining <- round(max(0, (total_expected - total_sims) / rate), 2)
        } else {
          rate <- "..."
          remaining <- "..."
        }
        cat(sprintf("PipeMaster:: %d/%d sims (~%s sims/h) | ~%s h remaining | %d/%d workers done\n",
                    total_sims, total_expected, rate, remaining, done_count, ncores))
        prev_total_sims <- total_sims
        prev_done_count <- done_count
      }

      if(done_count >= ncores) break
    }

    cat("Compiling results from workers", sep = "\n")
    outfile <- file.path(abs.path, paste0("SIMS_", output.name, ".txt"))
    for(w in 1:ncores) {
      wf <- file.path(abs.path, paste0(".worker_", w), paste0("SIMS_", output.name, ".txt"))
      if(file.exists(wf)) {
        worker_data <- readLines(wf)
        if(length(worker_data) > 0) {
          cat(paste(worker_data, collapse = "\n"), "\n", file = outfile, append = TRUE, sep = "")
        }
      }
      unlink(file.path(abs.path, paste0(".worker_", w)), recursive = TRUE)
      f <- file.path(abs.path, paste0(".worker_", w, ".done"))
      if(file.exists(f)) file.remove(f)
    }
    file.remove(file.path(abs.path, ".PM_worker_params.RData"))
    file.remove(file.path(abs.path, ".PM_worker.R"))
    for(w in 1:ncores) {
      f <- file.path(abs.path, paste0(".worker_", w, ".log"))
      if(file.exists(f)) file.remove(f)
    }

    end.time <- Sys.time()
    elapsed_h <- as.numeric(difftime(end.time, start.time, units = "hours"))
    cat(paste0("PipeMaster:: Done! ", total_expected, " simulations in ",
               round(elapsed_h, 3), " hours (~", round(total_expected / elapsed_h), " sims/h)"), "\n")

  } else {
    # === SINGLE CORE (batch: pre-sample params, single .Call per block) ===
    nloci_rows <- nrow(locfile)
    npop_loc <- as.numeric(model$I[1,3])

    sim.func <- function(arg) {
      # Pre-sample all parameters for the block (no disk I/O in this loop)
      commands <- character(block.size)
      mu_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
      rec_mat <- NULL
      par_list <- vector("list", block.size)

      for(i in 1:block.size) {
        if(is.numeric(mu.rates) && length(mu.rates) == 1) {
          rates <- list(rep(mu.rates, nloci_rows), c(mu.rates, 0))
        } else if(is.list(mu.rates)) {
          rates <- do.call(mu.rates[[1]], args = as.list(mu.rates[2:length(mu.rates)]))
          rates <- rep(rates, each = npop_loc)
          rates <- list(rates, c(0, 0))
        } else {
          rates <- sample.mu.rates(model)
        }
        mu_mat[, i] <- rates[[1]]

        if(is.numeric(rec.rates) && length(rec.rates) == 1) {
          r.rates <- rep(rec.rates, nloci_rows)
          if(is.null(rec_mat)) rec_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
          rec_mat[, i] <- r.rates
        } else if(is.list(rec.rates)) {
          r.rates <- do.call(rec.rates[[1]], args = as.list(rec.rates[2:length(rec.rates)]))
          r.rates <- rep(r.rates, each = npop_loc)
          if(is.null(rec_mat)) rec_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
          rec_mat[, i] <- r.rates
        }

        com <- msABC.commander(model, use.alpha = use.alpha, arg = arg)
        commands[i] <- com[[1]]
        par_list[[i]] <- c(com[[2]][2, ], rates[[2]])
        names(par_list[[i]]) <- c(com[[2]][1, ], "mean.rate", "sd.rate")
      }

      # Write locfile ONCE (static data; mu/rec overridden in C)
      write.table(locfile, paste(".", arg, "locfile.txt", sep = ""),
                  row.names = FALSE, col.names = TRUE, quote = FALSE, sep = " ")

      # Single C call processes entire block
      outputs <- .Call("msABC_batch_call", commands, mu_mat, rec_mat,
                       PACKAGE = "PipeMaster")

      # Parse all outputs (vectorized, no per-iteration rbind)
      sumstats_list <- lapply(strsplit(outputs, "\n", fixed = TRUE), function(lines) {
        tab <- read.table(text = lines, header = TRUE, sep = "\t")
        tab <- subset(tab, select = -c(X))
        cols <- grep("thomson", colnames(tab))
        cols <- c(cols, grep("ZnS", colnames(tab)))
        cols <- c(cols, grep("FayWuH", colnames(tab)))
        cols <- c(cols, grep("fwh", colnames(tab)))
        if(length(cols) != 0) tab <- tab[, -cols]
        tab
      })

      sumstats_mat <- do.call(rbind, sumstats_list)
      par_mat <- do.call(rbind, par_list)
      data.frame(cbind(par_mat, sumstats_mat))
    }

    total.sims <- 0
    for(j in 1:nsim.blocks) {
      start.time <- Sys.time()
      simulations <- sim.func(1)

      cat("Writing simulations to file", sep = "\n")
      write.table(simulations, file = paste("SIMS_", output.name, ".txt", sep = ""),
                  quote = FALSE, row.names = FALSE, col.names = FALSE, append = TRUE, sep = "\t")

      end.time <- Sys.time()
      total.sims <- total.sims + block.size
      cycle.time <- (as.numeric(end.time) - as.numeric(start.time)) / 60 / 60
      total.time <- cycle.time * nsim.blocks
      passed.time <- cycle.time * j
      remaining.time <- round(total.time - passed.time, 3)
      cat(paste("PipeMaster:: ", total.sims, " (~", round(block.size / cycle.time),
                " sims/h) | ~", remaining.time, " hours remaining", sep = ""), "\n")
    }
    f <- ".1locfile.txt"
    if(file.exists(f)) file.remove(f)
    print("Done!")
  }
}


#' Simulate both summary statistics and SFS in a single coalescent pass
#' @description This function simulates both summary statistics and the Site Frequency Spectrum
#'              from a single coalescent simulation run, cutting simulation time in half compared
#'              to running \code{sim.sumstat()} and \code{sim.sfs()} separately. The output is
#'              written to a single file with columns: parameters | summary statistics | SFS bins.
#' @param model A model object built by the main.menu.gui() function.
#' @param nsim.blocks Number of blocks to simulate. Total simulations = nsim.blocks x block.size (x ncores).
#' @param block.size Number of simulations per block. Default is 10.
#' @param path Path to write the output. Default is working directory.
#' @param output.name String. The prefix of the output file names.
#' @param use.alpha Logical. If TRUE the most recent population size change will be exponential. Default is FALSE.
#' @param mu.rates List. Distribution to sample mutation rates. See \code{sim.sumstat()} for details.
#' @param rec.rates List. Distribution to sample recombination rates. See \code{sim.sumstat()} for details.
#' @param one.snp Logical. If TRUE, one segregating site is randomly sampled per locus for the SFS. Default is FALSE.
#' @param folded Logical. If TRUE the SFS will be folded. Default is FALSE.
#' @param method Character string: \code{"stochastic"} (default) or \code{"expected"} for SFS computation.
#' @param monomorphic Logical. If TRUE, a monomorphic bin is prepended to the SFS. Default is FALSE.
#' @param append.sims Logical. If TRUE simulations will be appended. Default is FALSE.
#' @param ncores Number of cores for parallel execution. Default is 1.
#' @return Writes \code{SIMS_<output.name>.txt} with columns: parameters, summary statistics, and SFS bins.
#' @author Marcelo Gehara
#' @export
sim.all.stats <- function(model, nsim.blocks, block.size = 10,
                          path = getwd(), output.name,
                          use.alpha = FALSE,
                          mu.rates = NULL, rec.rates = NULL,
                          one.snp = FALSE, folded = FALSE,
                          method = c("stochastic", "expected"),
                          monomorphic = FALSE,
                          append.sims = FALSE, ncores = 1) {

  WD <- getwd()
  method <- match.arg(method)

  if(class(model) != "Model") {
    stop("First argument should be an object of class Model generated by the main.menu.gui() function.")
  }
  if(model$I[1,1] == "genomic") {
    stop("You need to get the data structure first. See function get.data.structure")
  }

  # Validate uniform per-population sample sizes across all loci (SFS requirement)
  npop <- as.numeric(model$I[1, 3])
  pop_cols <- 4:(3 + npop)
  pop_sizes_mat <- matrix(as.numeric(model$I[, pop_cols]), ncol = npop)
  if(nrow(unique(pop_sizes_mat)) > 1) {
    stop("All loci must have uniform per-population sample sizes for SFS simulation.\n",
         "  Use optimize.sfs.model() to downsample your model to uniform sample sizes first.")
  }

  pop_sizes_vec <- as.integer(pop_sizes_mat[1, ])
  nsam <- sum(pop_sizes_vec)

  setwd(path)
  on.exit(setwd(WD))

  locfile <- PipeMaster:::get.locfile(model)
  outfile <- paste0("SIMS_", output.name, ".txt")

  ############### Header discovery and writing
  if(append.sims == FALSE) {
    # Discover sumstat column names via one test run
    com <- PipeMaster:::msABC.commander(model, use.alpha = use.alpha, arg = 1)
    write.table(locfile, paste(".", 1, "locfile.txt", sep = ""),
                row.names = FALSE, col.names = TRUE, quote = FALSE, sep = " ")
    x <- strsplit(run.msABC(com[[1]]), "\t")
    ss.nam <- x[1][[1]]
    cols <- grep("thomson", ss.nam)
    cols <- c(cols, grep("ZnS", ss.nam))
    cols <- c(cols, grep("FayWuH", ss.nam))
    cols <- c(cols, grep("fwh", ss.nam))
    if(length(cols) != 0) ss.nam <- ss.nam[-cols]
    par.names <- c(com[[2]][1, ], "mean.rate", "sd.rate")

    # SFS column names
    if(npop == 1) {
      sfs_len <- floor(nsam / 2)
      if(folded) {
        folded_len <- length(fold_sfs(numeric(nsam - 1)))
        sfs.names <- paste0("sfs_fold_", seq(0, folded_len - 1))
      } else {
        sfs.names <- paste0("sfs_", seq(0, sfs_len - 1))
      }
    } else {
      idx_grid <- expand.grid(lapply(pop_sizes_vec, function(n) 0:n))
      sfs.names <- apply(idx_grid, 1, function(x) paste0("sfs_", paste(x, collapse = "_")))
    }
    if(monomorphic) {
      sfs.names <- c("sfs_mono", sfs.names)
    }

    # Single header: params | sumstats | SFS
    nam <- c(par.names, ss.nam, sfs.names)
    write.table(t(nam), file = outfile,
                quote = FALSE, row.names = FALSE, col.names = FALSE,
                append = FALSE, sep = "\t")
  }

  ############### Multi-core path
  if(ncores > 1) {
    abs.path <- normalizePath(getwd())

    # Clean up stale worker dirs and done files
    for(w in 1:ncores) {
      unlink(file.path(abs.path, paste0(".worker_", w)), recursive = TRUE)
      f <- file.path(abs.path, paste0(".worker_", w, ".done"))
      if(file.exists(f)) file.remove(f)
    }

    save(model, nsim.blocks, block.size, use.alpha, mu.rates, rec.rates,
         output.name, one.snp, folded, method, monomorphic,
         file = file.path(abs.path, ".PM_worker_params.RData"))

    worker_script <- paste(
      'args <- commandArgs(TRUE)',
      'worker_id <- as.integer(args[1])',
      'suppressMessages(library(PipeMaster))',
      sprintf('base_path <- "%s"', abs.path),
      'load(file.path(base_path, ".PM_worker_params.RData"))',
      'worker_dir <- file.path(base_path, paste0(".worker_", worker_id))',
      'dir.create(worker_dir, showWarnings=FALSE)',
      'sim.all.stats(model=model, nsim.blocks=nsim.blocks, block.size=block.size,',
      '              path=worker_dir, use.alpha=use.alpha, mu.rates=mu.rates,',
      '              rec.rates=rec.rates, one.snp=one.snp, folded=folded,',
      '              method=method, monomorphic=monomorphic, append.sims=TRUE,',
      '              output.name=output.name, ncores=1)',
      'write("done", file.path(base_path, paste0(".worker_", worker_id, ".done")))',
      'quit(save="no")',
      sep = "\n")
    writeLines(worker_script, file.path(abs.path, ".PM_worker.R"))

    start.time <- Sys.time()
    for(w in 1:ncores) {
      system(paste("Rscript", file.path(abs.path, ".PM_worker.R"), w,
                   ">", file.path(abs.path, paste0(".worker_", w, ".log")), "2>&1"),
             wait = FALSE)
    }
    cat(paste("PipeMaster:: Launched", ncores, "worker processes"), "\n")

    total_expected <- nsim.blocks * block.size * ncores
    prev_total_sims <- -1
    prev_done_count <- -1
    while(TRUE) {
      Sys.sleep(5)
      done_count <- sum(file.exists(file.path(abs.path, paste0(".worker_", 1:ncores, ".done"))))

      # Count sims across all workers
      total_sims <- 0
      for(w in 1:ncores) {
        wf <- file.path(abs.path, paste0(".worker_", w), paste0("SIMS_", output.name, ".txt"))
        if(file.exists(wf)) {
          n <- as.integer(system(paste("wc -l <", shQuote(wf)), intern = TRUE))
          if(!is.na(n) && n > 0) total_sims <- total_sims + n
        }
      }

      if(total_sims != prev_total_sims || done_count != prev_done_count) {
        elapsed_h <- as.numeric(difftime(Sys.time(), start.time, units = "hours"))
        if(elapsed_h > 0.001 && total_sims > 0) {
          rate <- round(total_sims / elapsed_h)
          remaining <- round(max(0, (total_expected - total_sims) / rate), 2)
        } else {
          rate <- "..."
          remaining <- "..."
        }
        cat(sprintf("PipeMaster:: %d/%d sims (~%s sims/h) | ~%s h remaining | %d/%d workers done\n",
                    total_sims, total_expected, rate, remaining, done_count, ncores))
        prev_total_sims <- total_sims
        prev_done_count <- done_count
      }

      if(done_count >= ncores) break
    }

    cat("Compiling results from workers", sep = "\n")
    outpath <- file.path(abs.path, outfile)
    for(w in 1:ncores) {
      wf <- file.path(abs.path, paste0(".worker_", w), outfile)
      if(file.exists(wf)) {
        worker_data <- readLines(wf)
        if(length(worker_data) > 0) {
          cat(paste(worker_data, collapse = "\n"), "\n", file = outpath, append = TRUE, sep = "")
        }
      }
      unlink(file.path(abs.path, paste0(".worker_", w)), recursive = TRUE)
      f <- file.path(abs.path, paste0(".worker_", w, ".done"))
      if(file.exists(f)) file.remove(f)
    }
    file.remove(file.path(abs.path, ".PM_worker_params.RData"))
    file.remove(file.path(abs.path, ".PM_worker.R"))
    for(w in 1:ncores) {
      f <- file.path(abs.path, paste0(".worker_", w, ".log"))
      if(file.exists(f)) file.remove(f)
    }

    end.time <- Sys.time()
    elapsed_h <- as.numeric(difftime(end.time, start.time, units = "hours"))
    cat(paste0("PipeMaster:: Done! ", total_expected, " simulations in ",
               round(elapsed_h, 3), " hours (~", round(total_expected / elapsed_h), " sims/h)"), "\n")

  } else {
    ############### Single-core path (combined C call)
    nloci_rows <- nrow(locfile)
    npop_loc <- as.numeric(model$I[1, 3])

    sim.combined.func <- function(arg) {
      # Pre-sample all parameters for the block
      commands <- character(block.size)
      mu_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
      rec_mat <- NULL
      par_list <- vector("list", block.size)

      for(i in 1:block.size) {
        if(is.numeric(mu.rates) && length(mu.rates) == 1) {
          rates <- list(rep(mu.rates, nloci_rows), c(mu.rates, 0))
        } else if(is.list(mu.rates)) {
          rates <- do.call(mu.rates[[1]], args = as.list(mu.rates[2:length(mu.rates)]))
          rates <- rep(rates, each = npop_loc)
          rates <- list(rates, c(0, 0))
        } else {
          rates <- sample.mu.rates(model)
        }
        mu_mat[, i] <- rates[[1]]

        if(is.numeric(rec.rates) && length(rec.rates) == 1) {
          r.rates <- rep(rec.rates, nloci_rows)
          if(is.null(rec_mat)) rec_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
          rec_mat[, i] <- r.rates
        } else if(is.list(rec.rates)) {
          r.rates <- do.call(rec.rates[[1]], args = as.list(rec.rates[2:length(rec.rates)]))
          r.rates <- rep(r.rates, each = npop_loc)
          if(is.null(rec_mat)) rec_mat <- matrix(0, nrow = nloci_rows, ncol = block.size)
          rec_mat[, i] <- r.rates
        }

        com <- msABC.commander(model, use.alpha = use.alpha, arg = arg)
        commands[i] <- com[[1]]
        par_list[[i]] <- c(com[[2]][2, ], rates[[2]])
        names(par_list[[i]]) <- c(com[[2]][1, ], "mean.rate", "sd.rate")
      }

      # Write locfile ONCE
      write.table(locfile, paste(".", arg, "locfile.txt", sep = ""),
                  row.names = FALSE, col.names = TRUE, quote = FALSE, sep = " ")

      # Single C call produces BOTH text output and SFS
      combined <- .Call("msABC_combined_batch_call", commands, mu_mat, rec_mat,
                        pop_sizes_vec, one.snp, method, monomorphic,
                        PACKAGE = "PipeMaster")

      # Parse sumstat text output (same as sim.sumstat)
      outputs <- combined[[1]]
      sumstats_list <- lapply(strsplit(outputs, "\n", fixed = TRUE), function(lines) {
        tab <- read.table(text = lines, header = TRUE, sep = "\t")
        tab <- subset(tab, select = -c(X))
        cols <- grep("thomson", colnames(tab))
        cols <- c(cols, grep("ZnS", colnames(tab)))
        cols <- c(cols, grep("FayWuH", colnames(tab)))
        cols <- c(cols, grep("fwh", colnames(tab)))
        if(length(cols) != 0) tab <- tab[, -cols]
        tab
      })
      sumstats_mat <- do.call(rbind, sumstats_list)

      # Process SFS
      sfs_mat <- combined[[2]]
      if(npop == 1 && !folded) {
        sfs_mat <- sfs_mat[, 1:floor(nsam / 2), drop = FALSE]
      }
      if(folded && npop == 1) {
        sfs_mat <- t(apply(sfs_mat, 1, fold_sfs))
      }
      if(monomorphic) {
        total_sites <- sum(as.numeric(model$loci[, 2]))
        mono_col <- total_sites - rowSums(sfs_mat)
        sfs_mat <- cbind(mono_col, sfs_mat)
      }

      par_mat <- do.call(rbind, par_list)
      data.frame(cbind(par_mat, sumstats_mat, sfs_mat))
    }

    total.sims <- 0
    for(j in 1:nsim.blocks) {
      start.time <- Sys.time()
      simulations <- sim.combined.func(1)

      cat("Writing simulations to file", sep = "\n")
      write.table(simulations, file = outfile,
                  quote = FALSE, row.names = FALSE, col.names = FALSE,
                  append = TRUE, sep = "\t")

      end.time <- Sys.time()
      total.sims <- total.sims + block.size
      cycle.time <- (as.numeric(end.time) - as.numeric(start.time)) / 60 / 60
      total.time <- cycle.time * nsim.blocks
      passed.time <- cycle.time * j
      remaining.time <- round(total.time - passed.time, 3)
      cat(paste("PipeMaster:: ", total.sims, " (~", round(block.size / cycle.time),
                " sims/h) | ~", remaining.time, " hours remaining", sep = ""), "\n")
    }
    f <- ".1locfile.txt"
    if(file.exists(f)) file.remove(f)
    print("Done!")
  }
}

